export const DEFAULT_CATEGORIES = [
  { code: "BUREAU_LOYER", name: "Bureau à domicile — loyer", deductionRate: 0, proofRequired: true },
  { code: "BUREAU_ENERGIE", name: "Bureau — énergie", deductionRate: 0, proofRequired: true },
  { code: "BUREAU_INTERNET", name: "Internet", deductionRate: 43, proofRequired: true },
  { code: "BUREAU_ASSURANCE", name: "Assurance habitation (quote-part)", deductionRate: 0, proofRequired: true },
  { code: "MATERIEL_ORDI", name: "Ordinateur", deductionRate: 100, proofRequired: true },
  { code: "MATERIEL_ECRAN", name: "Écran", deductionRate: 100, proofRequired: true },
  { code: "MATERIEL_TABLETTE", name: "Tablette", deductionRate: 100, proofRequired: true },
  { code: "MATERIEL_SMARTPHONE", name: "Smartphone", deductionRate: 40, proofRequired: true },
  { code: "MATERIEL_PERIPHERIQUE", name: "Périphériques", deductionRate: 100, proofRequired: true },
  { code: "MATERIEL_IMPRIMANTE", name: "Imprimante", deductionRate: 100, proofRequired: true },
  { code: "LOGICIEL_ADOBE", name: "Adobe Creative", deductionRate: 100, proofRequired: true },
  { code: "LOGICIEL_M365", name: "Microsoft 365", deductionRate: 100, proofRequired: true },
  { code: "LOGICIEL_IA", name: "Outils IA (Claude, ChatGPT…)", deductionRate: 100, proofRequired: true },
  { code: "LOGICIEL_LMS", name: "Plateforme LMS", deductionRate: 100, proofRequired: true },
  { code: "LOGICIEL_HEBERGEMENT", name: "Hébergement web", deductionRate: 100, proofRequired: true },
  { code: "LOGICIEL_CLOUD", name: "Stockage cloud", deductionRate: 100, proofRequired: true },
  { code: "LOGICIEL_CANVA", name: "Canva", deductionRate: 100, proofRequired: true },
  { code: "DEPLACEMENT_TC", name: "Transports en commun", deductionRate: 100, proofRequired: true },
  { code: "DEPLACEMENT_KM", name: "Indemnité kilométrique", deductionRate: 100, proofRequired: false },
  { code: "DEPLACEMENT_VOITURE", name: "Voiture (carburant, entretien)", deductionRate: 75, proofRequired: true },
  { code: "DEPLACEMENT_PARKING", name: "Parking", deductionRate: 75, proofRequired: true },
  { code: "FORMATION_COURS", name: "Cours / formation", deductionRate: 100, proofRequired: true },
  { code: "FORMATION_ELEARNING", name: "E-learning", deductionRate: 100, proofRequired: true },
  { code: "FORMATION_CONFERENCE", name: "Conférence", deductionRate: 100, proofRequired: true },
  { code: "FORMATION_LIVRES", name: "Livres professionnels", deductionRate: 100, proofRequired: true },
  { code: "FORMATION_PRESSE", name: "Presse spécialisée", deductionRate: 100, proofRequired: true },
  { code: "REPAS_AFFAIRES", name: "Repas d'affaires", deductionRate: 69, proofRequired: true },
  { code: "RECEPTION", name: "Réception clients", deductionRate: 50, proofRequired: true },
  { code: "CADEAUX", name: "Cadeaux d'affaires", deductionRate: 50, proofRequired: true },
  { code: "TELECOM_MIXTE", name: "Télécom mixte", deductionRate: 43, proofRequired: true },
  { code: "TELECOM_PRO", name: "Télécom professionnel dédié", deductionRate: 100, proofRequired: true },
  { code: "BANQUE_COMPTE", name: "Frais bancaires", deductionRate: 100, proofRequired: true },
  { code: "BANQUE_PLATEFORME", name: "Frais plateformes paiement", deductionRate: 100, proofRequired: true },
  { code: "ASSURANCE_RC", name: "RC professionnelle", deductionRate: 100, proofRequired: true },
  { code: "ASSURANCE_INCAPACITE", name: "Assurance incapacité", deductionRate: 100, proofRequired: true },
  { code: "PENSION_PLCI", name: "PLCI", deductionRate: 100, proofRequired: true },
  { code: "PENSION_PLCI_SOCIALE", name: "PLCI sociale", deductionRate: 100, proofRequired: true },
  { code: "SOCIAL_COTISATIONS", name: "Cotisations sociales", deductionRate: 100, proofRequired: true },
  { code: "HONORAIRES_COMPTABLE", name: "Honoraires comptable", deductionRate: 100, proofRequired: true },
  { code: "RECETTE", name: "Recette", deductionRate: 0, proofRequired: false },
  { code: "AUTRE", name: "Autre", deductionRate: 0, proofRequired: false },
];
